// THIS FILE IS AUTOGENERATED BY wb_intercon_gen
// ANY MANUAL CHANGES WILL BE LOST
module wb_intercon
   (input         wb_clk_i,
    input         wb_rst_i,
    input  [31:0] wb_vscale_i_adr_i,
    input  [31:0] wb_vscale_i_dat_i,
    input   [3:0] wb_vscale_i_sel_i,
    input         wb_vscale_i_we_i,
    input         wb_vscale_i_cyc_i,
    input         wb_vscale_i_stb_i,
    input   [2:0] wb_vscale_i_cti_i,
    input   [1:0] wb_vscale_i_bte_i,
    output [31:0] wb_vscale_i_dat_o,
    output        wb_vscale_i_ack_o,
    output        wb_vscale_i_err_o,
    output        wb_vscale_i_rty_o,
    input  [31:0] wb_vscale_d_adr_i,
    input  [31:0] wb_vscale_d_dat_i,
    input   [3:0] wb_vscale_d_sel_i,
    input         wb_vscale_d_we_i,
    input         wb_vscale_d_cyc_i,
    input         wb_vscale_d_stb_i,
    input   [2:0] wb_vscale_d_cti_i,
    input   [1:0] wb_vscale_d_bte_i,
    output [31:0] wb_vscale_d_dat_o,
    output        wb_vscale_d_ack_o,
    output        wb_vscale_d_err_o,
    output        wb_vscale_d_rty_o,
    output [31:0] wb_uart0_adr_o,
    output [31:0] wb_uart0_dat_o,
    output  [3:0] wb_uart0_sel_o,
    output        wb_uart0_we_o,
    output        wb_uart0_cyc_o,
    output        wb_uart0_stb_o,
    output  [2:0] wb_uart0_cti_o,
    output  [1:0] wb_uart0_bte_o,
    input  [31:0] wb_uart0_dat_i,
    input         wb_uart0_ack_i,
    input         wb_uart0_err_i,
    input         wb_uart0_rty_i,
    output [31:0] wb_rom0_adr_o,
    output [31:0] wb_rom0_dat_o,
    output  [3:0] wb_rom0_sel_o,
    output        wb_rom0_we_o,
    output        wb_rom0_cyc_o,
    output        wb_rom0_stb_o,
    output  [2:0] wb_rom0_cti_o,
    output  [1:0] wb_rom0_bte_o,
    input  [31:0] wb_rom0_dat_i,
    input         wb_rom0_ack_i,
    input         wb_rom0_err_i,
    input         wb_rom0_rty_i);

wire [31:0] wb_m2s_vscale_i_rom0_adr;
wire [31:0] wb_m2s_vscale_i_rom0_dat;
wire  [3:0] wb_m2s_vscale_i_rom0_sel;
wire        wb_m2s_vscale_i_rom0_we;
wire        wb_m2s_vscale_i_rom0_cyc;
wire        wb_m2s_vscale_i_rom0_stb;
wire  [2:0] wb_m2s_vscale_i_rom0_cti;
wire  [1:0] wb_m2s_vscale_i_rom0_bte;
wire [31:0] wb_s2m_vscale_i_rom0_dat;
wire        wb_s2m_vscale_i_rom0_ack;
wire        wb_s2m_vscale_i_rom0_err;
wire        wb_s2m_vscale_i_rom0_rty;
wire [31:0] wb_m2s_vscale_d_rom0_adr;
wire [31:0] wb_m2s_vscale_d_rom0_dat;
wire  [3:0] wb_m2s_vscale_d_rom0_sel;
wire        wb_m2s_vscale_d_rom0_we;
wire        wb_m2s_vscale_d_rom0_cyc;
wire        wb_m2s_vscale_d_rom0_stb;
wire  [2:0] wb_m2s_vscale_d_rom0_cti;
wire  [1:0] wb_m2s_vscale_d_rom0_bte;
wire [31:0] wb_s2m_vscale_d_rom0_dat;
wire        wb_s2m_vscale_d_rom0_ack;
wire        wb_s2m_vscale_d_rom0_err;
wire        wb_s2m_vscale_d_rom0_rty;

wb_mux
  #(.num_slaves (1),
    .MATCH_ADDR ({32'hf0000000}),
    .MATCH_MASK ({32'hfffffc00}))
 wb_mux_vscale_i
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i (wb_vscale_i_adr_i),
    .wbm_dat_i (wb_vscale_i_dat_i),
    .wbm_sel_i (wb_vscale_i_sel_i),
    .wbm_we_i  (wb_vscale_i_we_i),
    .wbm_cyc_i (wb_vscale_i_cyc_i),
    .wbm_stb_i (wb_vscale_i_stb_i),
    .wbm_cti_i (wb_vscale_i_cti_i),
    .wbm_bte_i (wb_vscale_i_bte_i),
    .wbm_dat_o (wb_vscale_i_dat_o),
    .wbm_ack_o (wb_vscale_i_ack_o),
    .wbm_err_o (wb_vscale_i_err_o),
    .wbm_rty_o (wb_vscale_i_rty_o),
    .wbs_adr_o ({wb_m2s_vscale_i_rom0_adr}),
    .wbs_dat_o ({wb_m2s_vscale_i_rom0_dat}),
    .wbs_sel_o ({wb_m2s_vscale_i_rom0_sel}),
    .wbs_we_o  ({wb_m2s_vscale_i_rom0_we}),
    .wbs_cyc_o ({wb_m2s_vscale_i_rom0_cyc}),
    .wbs_stb_o ({wb_m2s_vscale_i_rom0_stb}),
    .wbs_cti_o ({wb_m2s_vscale_i_rom0_cti}),
    .wbs_bte_o ({wb_m2s_vscale_i_rom0_bte}),
    .wbs_dat_i ({wb_s2m_vscale_i_rom0_dat}),
    .wbs_ack_i ({wb_s2m_vscale_i_rom0_ack}),
    .wbs_err_i ({wb_s2m_vscale_i_rom0_err}),
    .wbs_rty_i ({wb_s2m_vscale_i_rom0_rty}));

wb_mux
  #(.num_slaves (2),
    .MATCH_ADDR ({32'h90000000, 32'hf0000000}),
    .MATCH_MASK ({32'hffffffe0, 32'hfffffc00}))
 wb_mux_vscale_d
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i (wb_vscale_d_adr_i),
    .wbm_dat_i (wb_vscale_d_dat_i),
    .wbm_sel_i (wb_vscale_d_sel_i),
    .wbm_we_i  (wb_vscale_d_we_i),
    .wbm_cyc_i (wb_vscale_d_cyc_i),
    .wbm_stb_i (wb_vscale_d_stb_i),
    .wbm_cti_i (wb_vscale_d_cti_i),
    .wbm_bte_i (wb_vscale_d_bte_i),
    .wbm_dat_o (wb_vscale_d_dat_o),
    .wbm_ack_o (wb_vscale_d_ack_o),
    .wbm_err_o (wb_vscale_d_err_o),
    .wbm_rty_o (wb_vscale_d_rty_o),
    .wbs_adr_o ({wb_uart0_adr_o, wb_m2s_vscale_d_rom0_adr}),
    .wbs_dat_o ({wb_uart0_dat_o, wb_m2s_vscale_d_rom0_dat}),
    .wbs_sel_o ({wb_uart0_sel_o, wb_m2s_vscale_d_rom0_sel}),
    .wbs_we_o  ({wb_uart0_we_o, wb_m2s_vscale_d_rom0_we}),
    .wbs_cyc_o ({wb_uart0_cyc_o, wb_m2s_vscale_d_rom0_cyc}),
    .wbs_stb_o ({wb_uart0_stb_o, wb_m2s_vscale_d_rom0_stb}),
    .wbs_cti_o ({wb_uart0_cti_o, wb_m2s_vscale_d_rom0_cti}),
    .wbs_bte_o ({wb_uart0_bte_o, wb_m2s_vscale_d_rom0_bte}),
    .wbs_dat_i ({wb_uart0_dat_i, wb_s2m_vscale_d_rom0_dat}),
    .wbs_ack_i ({wb_uart0_ack_i, wb_s2m_vscale_d_rom0_ack}),
    .wbs_err_i ({wb_uart0_err_i, wb_s2m_vscale_d_rom0_err}),
    .wbs_rty_i ({wb_uart0_rty_i, wb_s2m_vscale_d_rom0_rty}));

wb_arbiter
  #(.num_masters (2))
 wb_arbiter_rom0
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i ({wb_m2s_vscale_i_rom0_adr, wb_m2s_vscale_d_rom0_adr}),
    .wbm_dat_i ({wb_m2s_vscale_i_rom0_dat, wb_m2s_vscale_d_rom0_dat}),
    .wbm_sel_i ({wb_m2s_vscale_i_rom0_sel, wb_m2s_vscale_d_rom0_sel}),
    .wbm_we_i  ({wb_m2s_vscale_i_rom0_we, wb_m2s_vscale_d_rom0_we}),
    .wbm_cyc_i ({wb_m2s_vscale_i_rom0_cyc, wb_m2s_vscale_d_rom0_cyc}),
    .wbm_stb_i ({wb_m2s_vscale_i_rom0_stb, wb_m2s_vscale_d_rom0_stb}),
    .wbm_cti_i ({wb_m2s_vscale_i_rom0_cti, wb_m2s_vscale_d_rom0_cti}),
    .wbm_bte_i ({wb_m2s_vscale_i_rom0_bte, wb_m2s_vscale_d_rom0_bte}),
    .wbm_dat_o ({wb_s2m_vscale_i_rom0_dat, wb_s2m_vscale_d_rom0_dat}),
    .wbm_ack_o ({wb_s2m_vscale_i_rom0_ack, wb_s2m_vscale_d_rom0_ack}),
    .wbm_err_o ({wb_s2m_vscale_i_rom0_err, wb_s2m_vscale_d_rom0_err}),
    .wbm_rty_o ({wb_s2m_vscale_i_rom0_rty, wb_s2m_vscale_d_rom0_rty}),
    .wbs_adr_o (wb_rom0_adr_o),
    .wbs_dat_o (wb_rom0_dat_o),
    .wbs_sel_o (wb_rom0_sel_o),
    .wbs_we_o  (wb_rom0_we_o),
    .wbs_cyc_o (wb_rom0_cyc_o),
    .wbs_stb_o (wb_rom0_stb_o),
    .wbs_cti_o (wb_rom0_cti_o),
    .wbs_bte_o (wb_rom0_bte_o),
    .wbs_dat_i (wb_rom0_dat_i),
    .wbs_ack_i (wb_rom0_ack_i),
    .wbs_err_i (wb_rom0_err_i),
    .wbs_rty_i (wb_rom0_rty_i));

endmodule
